### PR TITLE
Add nl-BE locale

### PR DESCRIPTION
**Pull request by Smile4ever**
Hi.

I was unsure about
```
<!ENTITY ForeBack.label              "xx=Fore yy=Back">
```
so I left it like I found it.

Also, I didn't translate the "installer" part. Just the files in locales/nl-BE/chrome.

Also, I added the locale to the list locales/all-locales. I wonder what the other locales are doing there, since I don't see them. Should they be removed? Or should they be imported from ChatZilla?

Thank you for looking at this.

### CODE REVIEW

**Comment by Smile4ever** [comment]
Please let me know if the install.rdf file is required. If so, let me know the location where I should put it.

**Comment by Ascrod** [comment]
"Fore" and "Back" are short for "Foreground" and "Background". If there are equivalent short terms for those words in Dutch, you should use those.

> I didn't translate the "installer" part.

That's fine. I would leave those files out if you decide not to translate them.

> Also, I added the locale to the list locales/all-locales.

Should be okay. Don't add en-US to that list though, as I think the file is only supposed to list locales that are not en-US.

> I wonder what the other locales are doing there

Those are for the existing ChatZilla localizations, and they are located in the l10n-central repository:
https://hg.mozilla.org/l10n-central/AB-CD/file/tip/extensions/irc/
Where "AB-CD" is the locale code. They can be ported, but they will also need updates similar to what you have done before they will work. I have not included them at this time.

> Please let me know if the install.rdf file is required. If so, let me know the location where I should put it.

You won't need to commit an install.rdf file, but if you decide to build the langpack yourself you will need to make one.

For the locale code, it looks like Pale Moon and Firefox translators don't distinguish between different Dutch dialects - they just use "nl" rather than "nl-NL", "nl-BE", etc. I'd prefer to be as consistent as possible with Pale Moon/Firefox locale codes and just use "nl" for the locale name here.

**Comment by Smile4ever** [comment]
Thanks for all the info, I am working on it.

**Comment by Ascrod** [comment]
Unfortunately this PR has bitrotted quite a bit, and at present I won't be able to use the build system to build locales or localized installers. You're still welcome to contribute the locale files and even create your own language pack if you wish; if so, please open a new PR with an updated translation.

Thanks!

**Pull request closed without merging**
